dependencies:
  - coverage
  # legacy
  - google-api-python-client
  - google-auth
  - numpy
  # legacy
  - psycopg2
  # Ensure a bit of discipline
  - pyiem >=1.26
  # testing
  - pytest
  - pytest-cov
  # legacy stuff
  - smartsheet-python-sdk
  # for pandas
  - sqlalchemy
  # testing
  - werkzeug
